apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-config
  namespace: infisical
  labels:
    app.kubernetes.io/name: infisical
    app.kubernetes.io/part-of: infisical
data:
  SITE_URL: "https://vault.marshallku.dev"
  REDIS_URL: "redis://infisical-redis.infisical.svc.cluster.local:6379"
  HOST: "0.0.0.0"
  PORT: "8080"
  HTTPS_ENABLED: "false"
  TELEMETRY_ENABLED: "false"
  NODE_ENV: "production"
