kind: Service
metadata:
  name: sealed-secrets-metrics
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-2.18.4
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.36.1
    app.kubernetes.io/part-of: sealed-secrets
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 8081
      targetPort: metrics
      protocol: TCP
      nodePort: null
  selector:
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/instance: sealed-secrets
# Source: sealed-secrets/templates/deployment.yaml
apiVersion: apps/v1
