---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: maji
spec:
  encryptedData:
    .dockerconfigjson: AgB4y2pt+bZLoLR1XlUKAy++bKU8ih5wnjDmSpYkt4BmfUR0txLzggTLmJDOkc3vSiFrsRVUebwcHkHSgjlZyNl9u7wnNBFfNKqEiRe63wU1QB999bXG8gmXs49VFyKDye+tw/aFm8POfIso/gm/67p+D00Byc8k6axLd4Yf3M52QngnkjdjSAHavO3t6MWwdBapCfjUf3sBkDzfXqskUsZGPAoS/w6WyyYHUgv25UAtVu3oWa0bDnJ8I00Gc95xg5oqFK4i9dXObC7c+/i8h51XlVO/LeY9uWeddVMqfVXthkDbTHo098bB5WORut9jlRjJVySpMYBTj43WG993thpUzTNA0ePeJNfBIVwk8ROcX4T7IPuC4+mOi95jmWdBdUxEK1UzVDHXTyP2RT8PRccPS5EnhOJGV/AMKiPpojxqarXezwdq2C1po7RNtKFxlpWEAbO5LufDBXlIRqtY3DCd9M9dH4kj1vBYE+E3isqhdSAIw9BpwDy34SU5shhwghfXZgX+tuJNuEtrt8L4sSNTUA50WSw3G1YTqErXNTojl0Uen1WE9a6Og2hQov6P0NXl+EOljtqERmpsHmXX/s2Y+m2v2J2iB+6uctsjOjPbL3+Qbe95bwMIxyOt4X8O/lC2WIRmZHCs00lRS07wlpRXwA8ZFwarso+ho2QvZH2ha5JhrUmMxT6ay9ctH4d//bpp7fzf65AIhXACXk4ts/NJxI23JemiE5RBX979IH7/XBNzhcDlVJolIColTYWmu0FG+Prw7VCC+QTmyhsazDd/vuuaQqprFFhX5rLvzZkwvreuMk4jzvMtulLeLoThaEbpCtbdCJA=
  template:
    metadata:
      name: ghcr-secret
      namespace: maji
    type: kubernetes.io/dockerconfigjson
