apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: irang-secret
  namespace: irang
spec:
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: irang-prd
        envSlug: prd
        secretsPath: "/"
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: irang
  managedSecretReference:
    secretName: irang-secret
    secretNamespace: irang
    creationPolicy: Owner
