---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: irang-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAU6RhrW/xCcuiCcjCKgwhRW9tltEfrfwlGePVCQTgxGI3YDCXAICRlETyfN0Kshut/bi6cbtky+j4Qy6/M6ARsMo3FVrPeuIzxJmYX0KSBFD8JqpCFw2TTAq/oqKexaOl/eawD71kqLjfsYG1F1Prhku6NiMrlpyfj/aXJDIX0PgwrGYBu2ZtIZsMoLVXokACwsdGDKvAWzFnj3e47/VzFjWXIZjCJ7J0y953OpE+Q/o3bMbjQjyHGn9x39BEvkAAaVXZ2Q3mCInaX2Nf5Ab7BNiyBqY92uVaKGdMsJxWtACK9YJMw0AgrKa3UgITzWXkUXZ1HrmaY1nPebyl62N8QhYql4rDp4DEmBrJbSrbtK0cJq3aErKemvinUjQQV1lMty9JoFc8175qRfflLLee0rMERF4oYrofg6415gtp41h89nxOIgNeAdoHCTB9DA3Wh2dsHjW1AKcIRD/kEhT5O5EKkFiAJPmo8HNeyeVFQm8BWHPYZP0IJIy9A4QAlvdPsOicwUp6FzzvQ0aiaN88u96Nt/Y+ZzJiyWthkpApf9OjFp002S5ECUiLYJCFfvwsSeWCsUEYcm2AieWP1sGOdfEELl3ng18Hg/RjxoDPCQ2ldgN3jsNbn9DLR/YrTUEIo8MqNuVYA2PHiIk/IMvS6PVAGSoO5mT/rDsxyWd7THzH61Pg39OxMky51IbzDRxabLa1X3MYzpAASrSS4U65zZPayApMdJVWfbCz2OXrAHAvDhiR7AO4AVQH+hOGvsbFGo22mTMRaLSEQoiLCgRAA3qBdz0PJMEed/dPj+pI/8kUEAjk9NvjQzHkwoDtfK5NYRbnFV88=
  template:
    metadata:
      name: ghcr-secret
      namespace: irang-dev
    type: kubernetes.io/dockerconfigjson
