---
# Source: secrets-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infisical-secre-controller-manager
  namespace: infisical-operator
  labels:
    helm.sh/chart: secrets-operator-v0.10.33
    app.kubernetes.io/name: secrets-operator
    app.kubernetes.io/instance: infisical-secrets-operator
    app.kubernetes.io/version: "v0.10.33"
    app.kubernetes.io/managed-by: Helm
  annotations:
    {}
