apiVersion: apps/v1
kind: Deployment
metadata:
  name: maji-frontend
  namespace: maji
  labels:
    app: maji-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maji-frontend
  template:
    metadata:
      labels:
        app: maji-frontend
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      nodeSelector:
        kubernetes.io/hostname: dev01
      containers:
        - name: frontend
          image: ghcr.io/80rian/maji-frontend:cb88c60cd44e78933c932b5cbd04bb29d244079c
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              value: http://maji-api:8080
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 15
