{
 "title": "Container Monitoring",
 "tags": [
  "kubernetes",
  "containers"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{job=\"kubelet-cadvisor\"}, node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\"}, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod, container)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory Working Set per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod, container)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Network Receive per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"kubelet-cadvisor\", pod!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Network Transmit per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet-cadvisor\", pod!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod)",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Read per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod, container)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Disk Write per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod, container)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory RSS per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod, container)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory Cache per Container",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_cache{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod, container)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage % (of limit)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod, container) / (sum(container_spec_memory_limit_bytes{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod, container) > 0) * 100",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "CPU Usage Overview",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod, container)",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  },
  {
   "title": "Pod Overview Table",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(label_join(sum(rate(container_cpu_usage_seconds_total{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod), \"pod_key\", \"/\", \"namespace\", \"pod\")) by (pod_key)"
    },
    {
     "expr": "sum(label_join(sum(container_memory_working_set_bytes{job=\"kubelet-cadvisor\", container!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}) by (namespace, pod), \"pod_key\", \"/\", \"namespace\", \"pod\")) by (pod_key)"
    },
    {
     "expr": "sum(label_join(sum(rate(container_network_receive_bytes_total{job=\"kubelet-cadvisor\", pod!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod), \"pod_key\", \"/\", \"namespace\", \"pod\")) by (pod_key)"
    },
    {
     "expr": "sum(label_join(sum(rate(container_network_transmit_bytes_total{job=\"kubelet-cadvisor\", pod!=\"\", node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval])) by (namespace, pod), \"pod_key\", \"/\", \"namespace\", \"pod\")) by (pod_key)"
    }
   ]
  }
 ]
}