apiVersion: v1
kind: PersistentVolume
metadata:
    name: grafana-pv
    labels:
        app: grafana
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: ""
    hostPath:
        path: /var/lib/k3s-data/grafana
        type: DirectoryOrCreate
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                            - k3s01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: grafana-data
    namespace: mgmt01
    labels:
        app: grafana
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: ""
    resources:
        requests:
            storage: 1Gi
    volumeName: grafana-pv
