---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitgarden-secret
  namespace: gitgarden
spec:
  encryptedData:
    GITHUB_TOKEN: AgBBFjTQSFZ2+BBbQuaYsM9/6QTSU+wLYbkYJ7/K4zvw07YC30R6I1b+cwzqptwSMCsNxRv6f2pNGtpAjh3qPDo99+jKjfsW/crOMpdxoI9UDbWfvmdURFWOJbAEh4dZW43EwrqimqridT/BZ3j8HE43UQlxGMEw+tCeJFmyH6/WqglkytArjttoJYTUi9+gix/thW8z6Lsre1rVZ9vpqBzHJ2qLsezFgw6pPXOX7WRc6zBitKsT2JAwXbZZZ7E5eTqO17SwBL1JLepGgLQJ6rAXdjUiiaUwNRcD3xNmU3aYJVhNTP1nZs759RmE0CWFrs1/kZUt4/a0hyIIj+ehlJsfuGOvQCbYHTUvTmoIEu/EMC9/JQY+0S7j/i/zyWfecL/GWqH8D0nLX0vS4oJrVQxlgk0eapJ0Pl/gtTYQK2UjaitQ/FPO2dtzNz9NFyQzp6mfBxsptvYE+6FNNqkVb1Shcu2UJN722BErJaxb7Jw26yKUmJBCWOqYb6hrJAs7yfR8s8R2LIT/b0/cYlnfwkP/jKXM2yRnRE5+2AIfN7L9/tFGTBPDZcsuDNvvm300JXTPItKJZVXhWlpnQv8Gp8WLmDRaVrnzlQsc9YZE87Rq+JMbzNj0BK8mSksHL/syBX+XUnQd2PYd6UDPpELnvgfTs0AOiyUDUGZC+pq/Wh1pJ5RkmgJDlhxYg5/ykAQaSp0JGkcTzWKEAQs4O5TY9FC9RC4QAhqgf1yIWftpxDazPsu7GXJadn77
  template:
    metadata:
      name: gitgarden-secret
      namespace: gitgarden
