---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: maji-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAkHt29q94n9MF04j9q/g5Y7qCsA7Fulm0lsBqJ9+FIMXuHm/W5ZsbpFJZkrucd71T+50wedpsYal6qnfef0whMPNAnsiXHISLUuDI9q3L+EwgWMsO2kYcPKa1LiO8C0lKPzUwVjfitKgEnEoqvvkZCnahnl6LkYPQENlpg26qi8AG14lcyA0Txc1Z9QwIto2KgnoFaHVAHKtN/uwBJRkiJNFqZc5Nim2DZmZmAej+oDPDcsXn9Un4ZMNpZMhHBNTtxoFgh3cGsvor9DqiFDciM/yCrqlhBwav6CvKFfUY5aIA5tHWLOdv+b4UXcaVzF9OpPZkeAJxrM7nC1i7rx0NDX1uGGKH5NHlkZV9iodphWTzZfAVfAEKEz64c1vQ0OVhAEK5uoID12cJXt81K9q8QMr/wo2CstKmhMW/wlhcqtRoERB08KC5LnQGFDZuLmXS7XwWajsV7nAhJOCHRALoaJejJNRzvRD/nPDOU2l/tBro+hj1VOh3f1eFXarzfpTf0raCsex+BiBB6w9Usc7L/Y0ot5+/AGA4MCXy8nqRksBFgQ26bC+5/hmjdVwbwVff08IJxK8qsClP7Gy4nUfh7TKSi5hhMoftiwKdkRkEsVhTIgwaR06FX2jObQXS9OnZWHNlPaOR1gK3UjlwNQECN1XFSjDdanriggDNHe0EyFKQu5HF1u2cpOnaTU7JiTx9dQtTJNh0aBvya2BQ4XgjZgEcQHOVVpw9DtoTL16tbYE5vNLPtqb6sCVrlQ+Qv7Vmj9qG8Xl2Ci4owxlGSGUbtFMiF27Jnuc+hhEgzlE6GTSQU3TKbDhkycpS5ELMsZSlZNFrOj0Y=
  template:
    metadata:
      name: ghcr-secret
      namespace: maji-dev
    type: kubernetes.io/dockerconfigjson
