---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: life-wiki
spec:
  encryptedData:
    .dockerconfigjson: AgAhDKS8711PyP7N+RTUxWntSEdoFfoRt7nmPvgv14jz1H2gKN98C3uboteAcFLgA8ne+mE3YyMpAm3AlX4yAticWDM4jupj0M7oNp+0vBdmfeaIv1hAUtMWJA6EsXiNuqpAOgssl28zmwGB07+dx8qc1HAqah0ioiaRlsO9B+fCgLlwCLB7x1F4fd1Nm//2SjkvQ17wfHPOW+bvjjLIZUqsWmT/yDeh+GQEi3iI0FxtTjdEVt0hnidGYaBjM1+zcXgrZB6gpdSwJ5qow05UDsHxu4bLhScE9UknrSW/YhjjZMBj8NlzoXF2LaeRgCjVihzFy1Z6MkrChxJls4pD63yl6KonxqYfNhZi5Hrdqeato4EMkeuquS1V0uuqBgqFji4FnuwEMTQATISspBfXodBBChW3pl0RcEd0dqDeh84PQ63BcWaUXC2Sae/NXkF6wSCQL9xVnHSXyN07IDBh4VcmdbPy/4Z3dIfwBKzEf4ys1jzGoIbGtaxVA3QJbznbIjuC8LY5Xm0u1OQEBT3MWNZL58oRDFi3nIfUEcPPGJAoVa3UbQe9d0aa9payRiH4bDj/3d3SZOVRcdppVmMEyUSX0Y9ldKS2oIuY/0LNJzYChy2G0bAKWcKrHWKe0muqIQqpTbg8boeG0wp3v7gM73bDT+rpNcxgikar7yi7jnw0YbiPdLe7PYOuv7dCBN9VRTqHVXbZ/ZU8Sjx/tsE57Aq3x+oflQ7XSSp0CIuBc0EjuGB4wy/y0T+qrtimi19KfP6nzg1bubB8Ean2wSFG7iHZZJn7KxrL5nXZD5MFh90XZNbNQJv8ChHd6sdxx5Km34Mp3bj12SM=
  template:
    metadata:
      name: ghcr-secret
      namespace: life-wiki
    type: kubernetes.io/dockerconfigjson
