kind: RoleBinding
metadata:
  name: sealed-secrets-service-proxier
  namespace: kube-system
  labels:
    app.kubernetes.io/name: sealed-secrets
    helm.sh/chart: sealed-secrets-2.18.4
    app.kubernetes.io/instance: sealed-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.36.1
    app.kubernetes.io/part-of: sealed-secrets
  annotations:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-service-proxier
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
# Source: sealed-secrets/templates/service.yaml
apiVersion: v1
