---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-token
  namespace: cloudflared-sssup
spec:
  encryptedData:
    token: AgCTZ1gTS7xn9yEYl1PrS4wtZchD+HRwlbWO4CkPux5wlmOCsiv3tc/JpoZRW+izvQziIAX+C5M0I5iOX+CWuqFn6POJ29c6OFl6Qy35RN45tqddmCYSJ9O7AncO0bVtSOzCj7Tbl9AepsPqZp/hmkiYiqi8YwDv3ZexmS2S0LLg+32JEX2xKz7V+QP+464Yd0bffHS3H2zgyP9sLW90b7JTVvKtOrTZYTU8HDP8GqvaXSuHDZQUNjF478i+6owHCW5rGu0+HynltUTTAKADOI7ObJP+ySqqAeO2AXzELm3+QIVG/NJsG/xzhoStB4sMy7W3DtdCHEw/ku98o+77WAV9sLjb9wG0v18C8rOyGzRxYWdTUsuM5YSMxJxevBmvWN1JtiD4rtxW0S/XZtYAASoq5SUn1CFp4jhn03VRKw1Mn2zAqJjxbxNaS+Q4u7GunT1CcafT6X0xg/fITWu4w8klb3Ss9z1xuPxrHBVAtUV4XWGXNIlK2uFg3dNDv0wNQB+kcomKdzgaoeP968JyZpLvDYha4L9eeIntSOVze7KB4fxa42hprij+bzUVRGXgJLmplyQTNjxjNFTlPNeXqwTJCCYxwW+vAN9spFBnkxTWr6S9I+vCVt7r/z1nusAgJS2/A80HdBRzvwx9FjtpAboXJHTaAo8AxbW0522WZx8dkvitGERh5lnGrNjppBaSFIHgtywG2bjAO4EgIamsrbU85YIJPfFr+KRnV8nbMOrtHQHiVOLucSwMVzbLSEDmPuFxRxMGLrMlw9CmNgNdlMBG3B9BsI5X1lLm1knbp468yq+98XVf2T0t2fnrpOAS2ha4rKMjyOYfDUyBQaXEiXvAn5+1HLsuvzBodFtr+mBKqM+CmFtT9z5icCbZxfhy5hTNReDahFLMTbgXaHW869Z1ue3mmtJ5+PLyH7+L0XlhVoIbyirs1eMD
  template:
    metadata:
      name: cloudflared-token
      namespace: cloudflared-sssup
    type: Opaque
