---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: dash
spec:
  encryptedData:
    .dockerconfigjson: AgBjlwY6oCQNRbgwA0zz6gmNAxsC4oi8BZBYlxvXa/aVWDugoHshHuiTjz1EcwRTnHVXnaTkVlDwU2rq9DtwhmAVnsx6I9EVWgeZW8bfRWaEfiD4eaEAaMJWxTn2VXpe1er25sQ92fVAGSdPZeisfN61EXQoTj96LVzVuuXv2fI24onRhvjYIYDrxqtZ1ZPGiL5yHTW25bd+YZfxHNXfkcNtvmhi+ucgk/wqdFDWN8JnGwjs/t92kvmB1oNrTizDrijJhwzQ+6aBOxKC0+d6vQs1CJe0blMJK+tVHUd0PYWIgLzCVnaGppyuAUr1TXeEiyLtwI/cR9p15RMogi2dpRIlxRy0tnaFNMmTYz5eI5wRt4UoPy5lZhic+MTQQQCpSv3Q4uzRWO9O1cnMhP8fJbk2ri2bJN2/hR8HwDEdcoaRbbI6q37jxhzF1Im0fGfqR9Ys8VlKtazNsTeLpod9VvEPVzqaXgz/EWGNjqxv/z/4mdmGJn4MxSSjCkbX4akr3DwTm5PfwzneFh4/VRHeJWTbCsFoSvsOpP+UfdNlTgtYbUzn5pEiD9W25EeBtzSvWzYoA86YYY28L4ISVubrxlQRS/oy02mtAzjJ0934+aQNj/H51oJNXFODp+EEzFHaUWv0eahUXJMVOfYUeHxrUVwgGODyWELWERH8k+x3si3cEycqSoI8FEVOYi70HeLrZ9AvPfRtYXS8j7Bq/i+dxM7LLTEByvAEKWwm6ZfzTEFSUV08g9GulEaAb6PIx01CF7Adufzj8a13/x8LDBFa4V+vlcBWwRBJG/tcQV0zGcfPjr3VBa8h983tVZ01+T6htC6eug8MR5s=
  template:
    metadata:
      name: ghcr-secret
      namespace: dash
    type: kubernetes.io/dockerconfigjson
